site:
  title: "Nathan Oesterle"
  start_page: about::index.adoc
  url: https://oesterle.io
content:
  sources:
    - url: https://github.com/noesterle/oesterle-antora
      branches: main
ui:
  bundle: 
    url: https://github.com/noesterle/antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
output:
  clean: true
