# This workflow will deploy the static website to the remote server.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install
          npx antora generate antora-playbook.yml
      - name: Deploy
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: oesterle.io
          USER: ${{secrets.DEPLOY_USER}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: docker/caddy/caddy-data/www/html/
          MODE: push
          SOURCE: build/site/
