# This workflow will deploy the static website to the remote server.

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install
          npx antora generate antora-playbook.yml --stacktrace
      - name: Test rsync restriction
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.DEPLOY_SSH_KEY}}" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "${{secrets.DEPLOY_KNOWN_HOST}}" > ~/.ssh/known_hosts

          CODE=1
          ssh -q -i ~/.ssh/private.key ${{secrets.DEPLOY_USER}}@oesterle.io
          SUCCESS=$?
          #echo $SUCCESS
          if [[ $SUCCESS != 0 ]]; then
            #echo "Task failed successfully"
            CODE=0
          fi
          exit $CODE
      - name: Deploy
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: oesterle.io
          USER: ${{secrets.DEPLOY_USER}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: .
          MODE: push
          SOURCE: build/site/
